messages:
  responses:
    start: "Вітаю, ций бот був розробленний для того, щоб швидко підібрати потрібну послугу для клієнта\n\nДля того, щоб отримати доступ до цього бота - натисніть “Нік”\n\nЯкщо ви вже придбали доступ - натисніть на кнопку “Увійти”"
    unknown-command: "Невідома команда"
    welcome: "Вітаю! Ви успішно ввійшли в акаунт"
    add-user: "Введіть юзер айді"
    no-auth: "Не вдалося ввійти, схоже що ви не придбали доступ, або він більше не дійсний"
    main-menu: "Головне меню"
    choose-thickness: "Оберіть густину волосся:"
    choose-a: "Оберіть структуру волосся за формою А-силует:"
    choose-curl: "Оберіть структуру волосся:"
    choose-damage: "Оберіть стадію пошкодження:"
    nick: "Зв'яжіться з адміністратором для придбання доступу: @arslovri (вместо этого будет ник администратора, если админов несколько то будет несколько ников)"
  errors:
    default: "Невідома помилка"
    err-no-access: "У вас немає доступу, ввійдіть в акаунт"
    err-no-admin: "Про вас немає записів в базі, зверніться до головного адміністратора"
    err-no-req: "Не знайдено такого юзер айді в базі"
    err-count-missing: "Сталася помилка, не знайдено ваших відповідей, почніть нове опитування"
    err-unlucky: "На жаль, для ваших параметрів не знайшлося процедури"